DROP DATABASE IF EXISTS `PORTAFOLIO`;
CREATE DATABASE `PORTAFOLIO` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `PORTAFOLIO`;


CREATE TABLE `TRABAJOS`(
    `COD_TRABAJO` TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `FECHA` DATE NOT NULL,
    `EMPRESA` VARCHAR( 20 ) NOT NULL,
    `CARGO` VARCHAR( 20 ) NOT NULL 
);

    INSERT INTO `TRABAJOS`
        ( `COD_TRABAJO`, `FECHA`, `EMPRESA`, `CARGO`)
    VALUES
        ( null, "2021-11-22", "PROGRAMAS SOL", "PROGRAMADORA" ),
        ( null, "2020-09-22", "PROGRAMAS LUNA", "GESTORA" ),
        ( null, "2019-08-22", "PROGRAMAS ESTRELLAS", "MAQUETADORA" );
        

CREATE TABLE `CONTENIDO`(
    `id` TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `titulo` VARCHAR( 40 ) NOT NULL,
    `fecha` DATETIME, 
    `comentarios` VARCHAR( 300 ) NOT NULL,
    `imagen` MEDIUMBLOB
); 